// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hafattxgixyxmegkhcab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhZmF0dHhnaXh5eG1lZ2toY2FiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3OTE1ODUsImV4cCI6MjA3MTM2NzU4NX0.y_ufk3pzZotqFYw8qpxEo6UbKV5lS0I_0h8FyqVr7Uc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});